# escape=`
FROM golang:1.14.0-windowsservercore-1809 AS builder

ARG REGISTRY_VERSION="v2.6.2"

WORKDIR C:\gopath\src\github.com\docker

RUN git clone https://github.com/docker/distribution.git; `
	cd distribution; `
	git checkout $env:REGISTRY_VERSION; `
	go build -o C:\out\registry.exe .\cmd\registry
	
FROM mcr.microsoft.com/windows/nanoserver:1809

ENV REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY="C:\data"

VOLUME ${REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY}
EXPOSE 5000

WORKDIR c:\registry
CMD ["registry","serve","config.yml"]
COPY --from=builder c:\out\registry.exe .
COPY --from=builder C:\gopath\src\github.com\docker\distribution\cmd\registry\config-example.yml .\config.yml







