# escape=`
ARG appbuild=mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019
ARG apprun=mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-ltsc2019

FROM $appbuild AS builder

WORKDIR C:\src\Docker.AtSea.Api
COPY dotnet\Docker.AtSea\Docker.AtSea.Api .

RUN nuget restore packages.config -PackagesDirectory ..\packages

RUN msbuild Docker.AtSea.Api.csproj /p:OutputPath=c:\out /p:Configuration=Release

# app image
FROM $apprun

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# configure IIS to write a global log file:
RUN Set-WebConfigurationProperty -p 'MACHINE/WEBROOT/APPHOST' -fi 'system.applicationHost/log' -n 'centralLogFileMode' -v 'CentralW3C'; `
    Set-WebConfigurationProperty -p 'MACHINE/WEBROOT/APPHOST' -fi 'system.applicationHost/log/centralW3CLogFile' -n 'truncateSize' -v 4294967295; `
    Set-WebConfigurationProperty -p 'MACHINE/WEBROOT/APPHOST' -fi 'system.applicationHost/log/centralW3CLogFile' -n 'period' -v 'MaxSize'; `
    Set-WebConfigurationProperty -p 'MACHINE/WEBROOT/APPHOST' -fi 'system.applicationHost/log/centralW3CLogFile' -n 'directory' -v 'c:\iislog'

ENV SA_PASSWORD="AtSe@!" `
    HOMEPAGE_URL=""

WORKDIR C:\Docker.AtSea.Api
RUN Remove-Website -Name 'Default Web Site'; `
    New-Website -Name 'Docker.AtSea.Api' `
                -Port 80 -PhysicalPath 'C:\Docker.AtSea.Api' `
                -ApplicationPool '.NET v4.5'

RUN & c:\windows\system32\inetsrv\appcmd.exe `
      unlock config `
      /section:system.webServer/handlers

HEALTHCHECK --interval=10s `
 CMD powershell -command `
    try { `
     $response = iwr http://localhost -UseBasicParsing; `
     if ($response.StatusCode -eq 200) { return 0} `
     else {return 1}; `
    } catch { return 1 }

ENTRYPOINT ["powershell"]
CMD Start-Process -NoNewWindow -FilePath C:\ServiceMonitor.exe -ArgumentList w3svc; `
    Invoke-WebRequest http://localhost -UseBasicParsing | Out-Null; `
    netsh http flush logbuffer | Out-Null; `
    Get-Content -path 'C:\iislog\W3SVC\u_extend1.log' -Tail 1 -Wait 

COPY --from=builder C:\out\_PublishedWebsites\Docker.AtSea.Api C:\Docker.AtSea.Api